question_data = [
    {"text": "The capital of Rajasthan is Jaipur.", "answer": "True"},
    {"text": "The Ganga River originates from Yamunotri Glacier.", "answer": "False"},
    {"text": "The Thar Desert is located in Rajasthan.", "answer": "True"},
    {"text": "The Himalayas are the oldest mountain range in the world.", "answer": "False"},
    {"text": "The Brahmaputra River enters India through Arunachal Pradesh.", "answer": "True"},
    {"text": "Mumbai is the capital of Maharashtra.", "answer": "True"},
    {"text": "Kerala is known as the 'Spice Garden of India'.", "answer": "True"},
    {"text": "The Sundarbans are located in Gujarat.", "answer": "False"},
    {"text": "Kaziranga National Park is famous for the one-horned rhinoceros.", "answer": "True"},
    {"text": "The Tropic of Cancer passes through Rajasthan.", "answer": "True"},

    {"text": "The Battle of Plassey was fought in 1757.", "answer": "True"},
    {"text": "Mahatma Gandhi launched the Quit India Movement in 1942.", "answer": "True"},
    {"text": "Bhagat Singh was hanged in 1931.", "answer": "True"},
    {"text": "The Constitution of India came into effect on 26 January 1950.", "answer": "True"},
    {"text": "Ashoka belonged to the Gupta Dynasty.", "answer": "False"},
    {"text": "The Red Fort was built by Shah Jahan.", "answer": "True"},
    {"text": "The Jallianwala Bagh massacre took place in Delhi.", "answer": "False"},
    {"text": "Subhas Chandra Bose founded the Indian National Army.", "answer": "True"},
    {"text": "The first Prime Minister of India was Jawaharlal Nehru.", "answer": "True"},
    {"text": "Sardar Vallabhbhai Patel was known as the Iron Man of India.", "answer": "True"},

    {"text": "Sachin Tendulkar is known as the 'God of Cricket'.", "answer": "True"},
    {"text": "Virat Kohli has won the ICC Cricket World Cup as captain.", "answer": "False"},
    {"text": "Rohit Sharma scored 264 runs in a men's ODI innings.", "answer": "True"},
    {"text": "MS Dhoni hit the winning six in the 2011 ODI World Cup Final.", "answer": "True"},
    {"text": "The first ICC Men's T20 World Cup was won by India.", "answer": "True"},
    {"text": "Jasprit Bumrah is a left-arm fast bowler.", "answer": "False"},
    {"text": "The IPL started in 2008.", "answer": "True"},
    {"text": "The Wankhede Stadium is located in Mumbai.", "answer": "True"},
    {"text": "Kapil Dev captained India to its first ODI World Cup victory.", "answer": "True"},
    {"text": "Ravindra Jadeja is a wicketkeeper.", "answer": "False"},

    {"text": "The national animal of India is the Bengal Tiger.", "answer": "True"},
    {"text": "The national anthem of India was written by Rabindranath Tagore.", "answer": "True"},
    {"text": "The Indian Parliament consists of Lok Sabha and Rajya Sabha only.", "answer": "False"},
    {"text": "New Delhi is the capital of India.", "answer": "True"},
    {"text": "The currency of India is the Rupee.", "answer": "True"},
    {"text": "ISRO stands for Indian Space Research Organisation.", "answer": "True"},
    {"text": "Chandrayaan-3 successfully landed near the Moon's south pole.", "answer": "True"},
    {"text": "The Peacock is the national bird of India.", "answer": "True"},
    {"text": "Hindi is the national language of India.", "answer": "False"},
    {"text": "The Lotus is the national flower of India.", "answer": "True"},

    {"text": "The Constitution of India is the longest written constitution in the world.", "answer": "True"},
    {"text": "The President of India is the head of the government.", "answer": "False"},
    {"text": "The Supreme Court of India is located in New Delhi.", "answer": "True"},
    {"text": "Goa became a state before Sikkim.", "answer": "False"},
    {"text": "The Konark Sun Temple is located in Odisha.", "answer": "True"},
    {"text": "India shares its longest international border with Bangladesh.", "answer": "True"},
    {"text": "The Indian flag has four colors.", "answer": "False"},
    {"text": "Dr. B. R. Ambedkar is known as the Father of the Indian Constitution.", "answer": "True"},
    {"text": "The Andaman and Nicobar Islands are located in the Arabian Sea.", "answer": "False"},
    {"text": "India celebrates Independence Day on 15 August.", "answer": "True"}
]